### PR TITLE
[rust] add a converter from concrete nodes to generic `Node`

### PR DESCRIPTION
**Pull request by froydnj**
The motivating example for this change is a visitor that wants to maintain parent node information as it traverses the AST.  The type of the stack maintained during the traversal should be `Vec<Node>`, but there's no way from the concrete nodes to upcast to the `Node` enum.

### CODE REVIEW

**Review by HParker — APPROVED** [review]
This pattern is also common in the C code, so makes sense you sometimes want a generic node.

**Comment by HParker** [comment]
@froydnj What do you think about a test here as well?

**Comment by froydnj** [comment]
@HParker done!  (Mostly just to make sure that `as_node()` compiles correctly.)

**Review by kddnewton — COMMENTED** [review]
Yeah just squash and then we can merge

**Comment by froydnj** [comment]
Squashed, thanks!

**Pull request merged**
